### ISSUE TITLE
File Upload does nothing

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#10]
Uploading a file does nothing and gives the following error in FireBug JavaScript Console:

TypeError: document.getElementById(...) is null
formData.append("curID",        document.getElementById('curID').value);
file.js (Zeile 88, Spalte 41)

**Comment by tomott** [comment]
Seems to be a caching problem on my installation.

**Comment by joachimdieterich** [comment]
Please context from where uploadframe is called.
