### ISSUE TITLE
"Benutzerkonten importieren" failed

### ISSUE THREAD

**Issue by tillenburg** [joachimdieterich/curriculum#11]
it causes the following Notification
"Sie haben 1 Hinweise:
Die Datei darf nicht größer als 0 MB sein"

**Comment by joachimdieterich** [comment]
Sideeffect of Issue #15. csv_size of your institution is 0. You can change this in your db -> table instiution -> csv_size (in byte). 

Also change: 
`paginator_limit` e.g. 30
 `avatar_size` e.g. 1048576
`material_size` e.g. 1048576
`acc_days` e.g. 7 
`timeout` e.g. 15 
`semester_id` should > 0 or NULL if no std_semester set.
 `file_id` id of file representing std. image for institutions
