### ISSUE TITLE
Verbesserungsvorschlag: Institution mit E-Mail-Adresse

### ISSUE THREAD

**Issue by tt33tt** [joachimdieterich/curriculum#169]
Hallo liebes Team,

in manchen Fällen ist der Administrator einer Institution nicht mehr erreichbar wegen defekter E-Mail-Adresse, Schulwechsel etc.
Daher würde ich gerne bei der Institution auch die offizielle E-Mail-Adresse/Telefonnummer optional hinterlegen können.

Liebe Grüße Florian

**Comment by joachimdieterich** [comment]
Damit die Funktion zur Verfügung steht, muss das Update ausgeführt werden.
