### ISSUE TITLE
Cannot find out which role a user has

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#19]
# Description
Role of user cannot be determined by webinterface.

# Steps to reproduce:
1. Create a new Institution 
2. Create a new User 
3. Mark checkbox of user
4. Move user to new Institution/Lehrer via 'Rolle zuweisen/einschreiben' 
5. 'Institution/Role' always shows default values

# Should be
Determine user role inside via web interface and reflect changes.

**Comment by tomott** [comment]
Institution and role might be displayed by clicking the 'Institution icon' next to the user.

**Comment by joachimdieterich** [comment]
commit 85110d3 fixes #19
