### ISSUE TITLE
Newly created user cannot log in

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#20]
# Description
After creating and loging in a new user with a new Institution as **Lehrer**, the dashboard displays a never ending box 'Loading' ...

# Logging output
Undefined offset: 7 in /var/www/curriculum/share/templates/compiled/10484d8a237f8f386a10a04d58207b376ea02ffe.file.dashboard.tpl.php on line 935
Undefined offset: 7 in /var/www/curriculum/share/templates/compiled/10484d8a237f8f386a10a04d58207b376ea02ffe.file.dashboard.tpl.php on line 935
Undefined offset: 7 in /var/www/curriculum/share/templates/compiled/10484d8a237f8f386a10a04d58207b376ea02ffe.file.dashboard.tpl.php on line 935
 Undefined variable: recent_mails in /var/www/curriculum/share/libs/Smarty-3.0.6/libs/sysplugins/smarty_internal_data.php on line 287
Trying to get property of non-object in /var/www/curriculum/share/classes/exception.class.php on line 35
Trying to get property of non-object in /var/www/curriculum/share/classes/exception.class.php on line 35
Trying to get property of non-object in /var/www/curriculum/share/classes/exception.class.php on line 35
PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null in /var/www/curriculum/share/classes/log.class.php on line 79
Uncaught CurriculumException:[1]: Als <strong>Sch\xc3\xbcler</strong> verf\xc3\xbcgen Sie nicht \xc3\xbcber die erforderliche Berechtigung (user:resetPassword).\n\n  thrown in /var/www/curriculum/share/function.php on line 286

**Comment by joachimdieterich** [comment]
role_id was not set. reason empty $USER->semester_id . solution #23
