### ISSUE TITLE
'Change password' i.e. confirmed setting of 3 makes login problems

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#21]
# Description
Setting a user confirmed property to 3 i.e. 'Change Password' makes a never ending modal appear.

# Logfile
PHP Warning:  PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null in /var/www/curriculum/share/classes/log.class.php on line 79
PHP Fatal error:  Uncaught CurriculumException:[1]: Als <strong></strong> verf\xc3\xbcgen Sie nicht \xc3\xbcber die erforderliche Berechtigung (user:resetPassword).\n\n  thrown in /var/www/curriculum/share/function.php on line 286

**Comment by joachimdieterich** [comment]
closed see #23
