### ISSUE TITLE
Automagically add 'Lernzeitraum' and 'Lerngruppe' when creating an institution

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#23]
# Description
The field semester_id for user must be set, otherwise strange things like #21 and #22.

# Should be
'Lernzeitraum' and 'Lerngruppe' should automagically added when creating an institution

**Comment by joachimdieterich** [comment]
- it should be possible to put user in no semester an group. (e.g. admins)
Possible solution: 
- if there is no semester, but multiple institution enrolments, user gets selector to toggle between those.
