### ISSUE TITLE
Fehler Institution Auswählen

### ISSUE THREAD

**Issue by tt33tt** [joachimdieterich/curriculum#266]
Ich wähle in der linken Seitenleiste eine Institution aus: Freiherr-von-Stein-Schule
Es springt dann aber immer auf die unterste Institution: Hessische Lehrkräfteakademie
Somit kann ich keine andere Institution wählen.

Ich vermute eine Verwandtschaft mit: #256 
https://github.com/joachimdieterich/curriculum/issues/256#ref-commit-0a37966

**Comment by joachimdieterich** [comment]
Dieser Bug tritt auf, wenn man an einer Institution, aber nicht in einer Lerngruppe eingeschrieben ist. 
-> kurzfristige Lösung. Man schreibt sich an den Institutionen in eine Lerngruppe ein. danach funktioniert das Menü wieder. 
Hintergrund:
Das Pull-Down Menü hat zwei funktionen. 
- Wechsel der Institution
- Wechsel des Lernzeitraums (an einer Institution)
Hier gibt es unter bestimmten Konstellationen den oben beschriebenen Fehler

**Comment by joachimdieterich** [comment]
Es handelt sich um keinen Bug. Wie oben beschrieben tritt das Verhalten nur auf, wenn Einschreibungen nicht sauber gemacht wurden. In der neuen Version (s. https://github.com/joachimdieterich/laravel-curriculum-adminlte3) wird das durch eine geänderte Verarbeitung der Daten verhindert)

**Comment by tt33tt** [comment]
ok, danke! Dann muss ich mich jetzt in alle Institutionen nicht nur als Admin, sondern auch in die Lerngruppen einschreiben
