### ISSUE TITLE
Missing context_id in where clause

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#28]
[Mon Aug 01 10:56:40.657106 2016] [:error] PHP Warning:  PDO::prepare(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'context_id' in 'where clause' in /var/www/curriculum/share/classes/db.class.php on line 74
[Mon Aug 01 10:56:40.657188 2016] [:error] PHP Fatal error:  Uncaught Error: Call to a member function execute() on boolean in /var/www/curriculum/share/classes/statistic.class.php:39\nStack trace:\n#0 /var/www/curriculum/public/index.php(57): Statistic->getAccomplishedObjectives('all')\n#1 {main}\n  thrown in /var/www/curriculum/share/classes/statistic.class.php on line 39

**Comment by joachimdieterich** [comment]
Solution: Update DB according to commit 0fe172c00b8aa406b1fc23ecc880dabdf166b006

Please take the following changes to keep db working

Changing 'user_accomplished'
- renamed 'enabling_objective_id' to 'reference_id'
- adding 'context_id'
- adding ON UPDATE CURRENT_TIMESTAMP to `accomplished_time`

Updating context table:
INSERT INTO `context` (`id`, `context`, `context_id`, `path`)
VALUES
(12, 'enabling_objective', 12, NULL);

Update user_accomplished
update user_accomplished set context_id = 12

INSERT INTO `context` (`id`, `context`, `context_id`, `path`)
VALUES
(13, 'task', 13, NULL);

**Comment by tomott** [comment]
Works. Perfekt.
