### ISSUE TITLE
Missing error message for referenced user on delete

### ISSUE THREAD

**Issue by tomott** [joachimdieterich/curriculum#5]
Deleting a user that is in use just failes without a message. The log gives:

PHP Warning:  PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`curriculum`.`curriculum`, CONSTRAINT `rel_cu_user` FOREIGN KEY (`creator_id`) REFERENCES `users` (`id`)) in /var/www/curriculum/share/classes/user.class.php on line 355, referer: [...]/public/index.php?action=user&paginator=userP&userP_sel_id=398

**Comment by joachimdieterich** [comment]
Wrong DB: Delete references connecting user table.
